version: '3'
services:
  itrp.poc.network.vpn:
    build: 
      context: ./VPN/
    depends_on:
      - dns
    image: itrp.poc.network.vpn:latest
    volumes:
      - ./config:/poc-data/
    ports:
    - "${DOCKER_PUBLIC_IP}500:500/udp"
    - "${DOCKER_PUBLIC_IP}4000:4000/udp"
  dns:
    build: 
      context: ./DNS/
    image: itrp.poc.network.dns:latest
    ports:
    - "${DOCKER_PUBLIC_IP}53:53/udp"
    - "${DOCKER_PUBLIC_IP}53:53/tcp"
    


